name: delivery_admin
description: Delivery Admin
autor: Cássio Meira Silva
version: 1.0.1+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.2

  # [Firebase]
  # firebase_core: ^0.4.4+3
  firebase_auth: ^0.16.0
  # cloud_firestore: ^0.13.5
  # firebase_storage: ^3.1.5
  firebase_messaging: ^6.0.15
  parse_server_sdk: ^1.0.26

  # [Widgets]
  modal_progress_hud: ^0.1.3
  image_picker: ^0.6.7+3
  photo_view: ^0.9.2
  flutter_local_notifications: ^1.4.0
  flutter_slidable: ^0.5.4
  font_awesome_flutter: ^8.8.1
  intro_slider: ^2.2.9
  carousel_slider: ^2.2.1
  keyboard_dismisser: ^1.0.2
  adaptive_dialog: ^0.7.5
  shimmer: ^1.1.1
  sticky_headers: ^0.1.8+1
  sliding_up_panel: ^1.0.2
  cached_network_image: ^2.2.0+1
  auto_size_text: ^2.1.0
  timeline_tile: ^0.1.2
  month_picker_dialog: ^0.3.2

  # [Outros]
  google_sign_in: ^4.3.0
  dio: ^3.0.9
  flutter_masked_text: ^0.8.0
  cpf_cnpj_validator: ^1.0.5
  shared_preferences: ^0.5.6+3
  path_provider: ^1.6.11
  url_launcher: ^5.4.11
  package_info: ^0.4.0+17
  logger: ^0.9.1
  get_it: ^4.0.2
  flutter_native_image: ^0.0.5+2

  # [Mapa]
  maps_launcher: ^1.2.0
  #flutter_map: ^0.8.2
  latlong: ^0.6.1
  #location: ^3.0.1
  #geopoint: ^0.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/